system:
  env: public
  db-type: mysql
  oss-type: local
  use-multipoint: true
  use-redis: true
mysql:
  path: 127.0.0.1
  port: "3306"
  config: charset=utf8mb4&parseTime=True&loc=Local
  db-name: admin
  username: root
  password: ""
  max-idle-conns: 10
  max-open-conns: 100
  log-mode: error
  log-zap: false
redis:
  db: 0
  addr: 127.0.0.1:6379
  password: ""
db-list:
- disable: false
  type: ""
  alias-name: ""
  path: ""
  port: ""
  config: ""
  db-name: ""
  username: ""
  password: ""
  max-idle-conns: 10
  max-open-conns: 100
  log-mode: ""
  log-zap: false
email:
  to: xxx@qq.com
  port: 465
  from: xxx@163.com
  host: smtp.163.com
  is-ssl: true
  secret: xxx
  nickname: test
zap:
  level: info
  format: json
  prefix: ''
  director: log
  show-line: true
  encode-level: LowercaseLevelEncoder
  stacktrace-key: stacktrace
  log-in-console: false
